// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace MigrationsTest.SqlProj
{
    public partial class Table1
    {
        public int Id { get; set; }
        public string Data { get; set; }
    }
}