// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScaffoldingTester.Models
{
    public partial class Customer
    {
        public Customer()
        {
            OrderLink = new HashSet<Order>();
            CustomerTypes = new HashSet<CustomerDemographic>();
        }

        public string CustomerId { get; set; }
        public string CompanyName { get; set; }
        public string ContactName { get; set; }
        public string ContactTitle { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Region { get; set; }
        public string PostalCode { get; set; }
        public string CountryRef { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public int Rating { get; set; }

        public virtual ICollection<Order> OrderLink { get; set; }

        public virtual ICollection<CustomerDemographic> CustomerTypes { get; set; }
    }
}