// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ScaffoldingTester.Models
{
    public partial class SpacesResult
    {
        [Column("ID Results Log")]
        public string IDResultsLog { get; set; }
        public string Sector { get; set; }
    }
}
