// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using NetTopologySuite.Geometries;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ScaffoldingTester.Models
{
    public partial class SpecialTypesResult
    {
        public int Id { get; set; }
        public Geometry Geo { get; set; }
        public byte[] Parents { get; set; }
        public Geometry Geom { get; set; }
    }
}
