// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ScaffoldingTester.Models
{
    public partial class TenMostExpensiveProductsResult
    {
        [StringLength(20)]
        public string TenMostExpensiveProducts { get; set; }
        public decimal? UnitPrice { get; set; }
    }
}
