// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ScaffoldingTester.Models
{
    public partial class TvpResult
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Total { get; set; }
    }
}
