// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScaffoldingPostgreSqlMultiSchemaTester.Models
{
    /// <summary>
    /// Cross-reference table mapping vendors with the products they supply.
    /// </summary>
    public partial class Productvendor
    {
        /// <summary>
        /// Primary key. Foreign key to Product.ProductID.
        /// </summary>
        public int Productid { get; set; }
        /// <summary>
        /// Primary key. Foreign key to Vendor.BusinessEntityID.
        /// </summary>
        public int Businessentityid { get; set; }
        /// <summary>
        /// The average span of time (in days) between placing an order with the vendor and receiving the purchased product.
        /// </summary>
        public int Averageleadtime { get; set; }
        /// <summary>
        /// The vendor&apos;s usual selling price.
        /// </summary>
        public decimal Standardprice { get; set; }
        /// <summary>
        /// The selling price when last purchased.
        /// </summary>
        public decimal? Lastreceiptcost { get; set; }
        /// <summary>
        /// Date the product was last received by the vendor.
        /// </summary>
        public DateTime? Lastreceiptdate { get; set; }
        /// <summary>
        /// The maximum quantity that should be ordered.
        /// </summary>
        public int Minorderqty { get; set; }
        /// <summary>
        /// The minimum quantity that should be ordered.
        /// </summary>
        public int Maxorderqty { get; set; }
        /// <summary>
        /// The quantity currently on order.
        /// </summary>
        public int? Onorderqty { get; set; }
        /// <summary>
        /// The product&apos;s unit of measure.
        /// </summary>
        public string Unitmeasurecode { get; set; }
        public DateTime Modifieddate { get; set; }

        public virtual Vendor Businessentity { get; set; }
        public virtual Product Product { get; set; }
        public virtual Unitmeasure UnitmeasurecodeNavigation { get; set; }
    }
}