// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScaffoldingPostgreSqlMultiSchemaTester.Models
{
    /// <summary>
    /// General purchase order information. See PurchaseOrderDetail.
    /// </summary>
    public partial class Purchaseorderheader
    {
        public Purchaseorderheader()
        {
            Purchaseorderdetail = new HashSet<Purchaseorderdetail>();
        }

        /// <summary>
        /// Primary key.
        /// </summary>
        public int Purchaseorderid { get; set; }
        /// <summary>
        /// Incremental number to track changes to the purchase order over time.
        /// </summary>
        public int Revisionnumber { get; set; }
        /// <summary>
        /// Order current status. 1 = Pending; 2 = Approved; 3 = Rejected; 4 = Complete
        /// </summary>
        public int Status { get; set; }
        /// <summary>
        /// Employee who created the purchase order. Foreign key to Employee.BusinessEntityID.
        /// </summary>
        public int Employeeid { get; set; }
        /// <summary>
        /// Vendor with whom the purchase order is placed. Foreign key to Vendor.BusinessEntityID.
        /// </summary>
        public int Vendorid { get; set; }
        /// <summary>
        /// Shipping method. Foreign key to ShipMethod.ShipMethodID.
        /// </summary>
        public int Shipmethodid { get; set; }
        /// <summary>
        /// Purchase order creation date.
        /// </summary>
        public DateTime Orderdate { get; set; }
        /// <summary>
        /// Estimated shipment date from the vendor.
        /// </summary>
        public DateTime? Shipdate { get; set; }
        /// <summary>
        /// Purchase order subtotal. Computed as SUM(PurchaseOrderDetail.LineTotal)for the appropriate PurchaseOrderID.
        /// </summary>
        public decimal Subtotal { get; set; }
        /// <summary>
        /// Tax amount.
        /// </summary>
        public decimal Taxamt { get; set; }
        /// <summary>
        /// Shipping cost.
        /// </summary>
        public decimal Freight { get; set; }
        public DateTime Modifieddate { get; set; }

        public virtual Employee Employee { get; set; }
        public virtual Shipmethod Shipmethod { get; set; }
        public virtual Vendor Vendor { get; set; }
        public virtual ICollection<Purchaseorderdetail> Purchaseorderdetail { get; set; }
    }
}