// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using ScaffoldingPostgreSqlMultiSchemaTester.Models.dboNs;
using ScaffoldingPostgreSqlMultiSchemaTester.Models.HumanResourcesNs;
using ScaffoldingPostgreSqlMultiSchemaTester.Models.PersonNs;
using ScaffoldingPostgreSqlMultiSchemaTester.Models.ProductionNs;
using ScaffoldingPostgreSqlMultiSchemaTester.Models.PurchasingNs;
using ScaffoldingPostgreSqlMultiSchemaTester.Models.SalesNs;


namespace ScaffoldingPostgreSqlMultiSchemaTester.Models.PurchasingNs
{
    /// <summary>
    /// Individual products associated with a specific purchase order. See PurchaseOrderHeader.
    /// </summary>
    public partial class PurchaseOrderDetail
    {
        /// <summary>
        /// Primary key. Foreign key to PurchaseOrderHeader.PurchaseOrderID.
        /// </summary>
        public int PurchaseOrderId { get; set; }
        /// <summary>
        /// Primary key. One line number per purchased product.
        /// </summary>
        public int PurchaseOrderDetailId { get; set; }
        /// <summary>
        /// Date the product is expected to be received.
        /// </summary>
        public DateTime DueDate { get; set; }
        /// <summary>
        /// Quantity ordered.
        /// </summary>
        public short OrderQty { get; set; }
        /// <summary>
        /// Product identification number. Foreign key to Product.ProductID.
        /// </summary>
        public int ProductId { get; set; }
        /// <summary>
        /// Vendor&apos;&apos;s selling price of a single product.
        /// </summary>
        public decimal UnitPrice { get; set; }
        /// <summary>
        /// Quantity actually received from the vendor.
        /// </summary>
        public decimal ReceivedQty { get; set; }
        /// <summary>
        /// Quantity rejected during inspection.
        /// </summary>
        public decimal RejectedQty { get; set; }
        /// <summary>
        /// Date and time the record was last updated.
        /// </summary>
        public DateTime ModifiedDate { get; set; }

        public virtual Product Product { get; set; }
        public virtual PurchaseOrderHeader PurchaseOrder { get; set; }
    }
}