// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace DockerPlayground.Models
{
    public partial class StoGetSomeDataResult
    {
        [StringLength(100)]
        public string? SomeName { get; set; }
        [StringLength(100)]
        public string? SomeValue { get; set; }
    }
}
