// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Issue3343.Models;

public partial class Issue3343Context : DbContext
{
    public Issue3343Context(DbContextOptions<Issue3343Context> options)
        : base(options)
    {
    }

    public virtual DbSet<TableOne> TableOnes { get; set; }

    public virtual DbSet<TableTwo> TableTwos { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TableOne>(entity =>
        {
            entity.HasKey(e => e.TableOneId).HasName("PK_dbo_TableOne");

            entity.ToTable("TableOne");
        });

        modelBuilder.Entity<TableTwo>(entity =>
        {
            entity.HasKey(e => e.TableTwoId).HasName("PK_dbo_TableTwo");

            entity.ToTable("TableTwo");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}