// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Issue3343.Models;

public partial class TableTwo
{
    public int TableTwoId { get; set; }
}