// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ScaffoldingTester.Models
{
    public partial class BoolNullableTest
    {
        public int Id { get; set; }
        public bool TestBool { get; set; }
        public DateTime? Noda { get; set; }
    }
}