// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;

namespace ScaffoldingTester.Models
{
    public partial class NorthwindContext
    {

        [DbFunction("GetCustInfo", "dbo")]
        public static string GetCustInfo(string Attribute, int? CustomerId)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("GetCustInfoNoParams", "dbo")]
        public static string GetCustInfoNoParams()
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }
    }
}
