// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ScaffoldingTester.Models
{
    public partial class Region
    {
        public Region()
        {
            RegionShippers = new HashSet<RegionShipper>();
            Territories = new HashSet<Territory>();
        }

        public int RegionId { get; set; }
        public string RegionDescription { get; set; }

        public virtual ICollection<RegionShipper> RegionShippers { get; set; }
        public virtual ICollection<Territory> Territories { get; set; }
    }
}