// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.Data.SqlClient;
using System;
using System.Data;
using System.Threading.Tasks;
using ConsoleApp.Models;

namespace ConsoleApp.Models
{
    public partial class ChinookContextProcedures
    {
        private readonly ChinookContext _context;

        public ChinookContextProcedures(ChinookContext context)
        {
            _context = context;
        }

        public async Task<GetTitlesResult[]> GetTitles(string Title, OutputParameter<int> returnValue = null)
        {
            var parameterTitle = new SqlParameter
            {
                ParameterName = "Title",
                Size = 200,
                Value = Title ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.NVarChar,
            };

            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var _ = await _context.SqlQuery<GetTitlesResult>("EXEC @returnValue = [dbo].[GetTitles] @Title", parameterTitle, parameterreturnValue);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
