// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DockerPlayground.Models;

public partial class Abc
{
    public int Id { get; set; }

    public string? Name { get; set; }

    public byte Type { get; set; }
}