// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using DockerPlayground.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace DockerPlayground.Models
{
    public partial class DockerPlaygroundContext
    {
        private IDockerPlaygroundContextProcedures? _procedures;

        public virtual IDockerPlaygroundContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new DockerPlaygroundContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IDockerPlaygroundContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class DockerPlaygroundContextProcedures : IDockerPlaygroundContextProcedures
    {
        private readonly DockerPlaygroundContext _context;

        public DockerPlaygroundContextProcedures(DockerPlaygroundContext context)
        {
            _context = context;
        }

        public virtual async Task<List<StoGetSomeDataResult>?> StoGetSomeDataAsync(OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<StoGetSomeDataResult>("EXEC @returnValue = [dbo].[StoGetSomeData]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
