// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace DockerPlayground.Models
{
    public partial class StoGetSomeDataLegacyDiscoveryResult
    {
        [StringLength(100)]
        public string? OrderName { get; set; }
        [StringLength(100)]
        public string? OrderValue { get; set; }
    }
}
