// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace DockerPlayground.Models
{
    public partial class StoGetSomeDataWithParametersResult
    {
        public int CategoryId { get; set; }
        [StringLength(50)]
        public string? SearchTerm { get; set; }
        [Column("Amount", TypeName = "decimal(10,2)")]
        public decimal Amount { get; set; }
    }
}
