// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace DockerPlayground.Models
{
    public partial class StoGetComputedExpressionShapesResult
    {
        public int? ArithmeticValue { get; set; }
        [StringLength(20)]
        public string? ConcatenatedText { get; set; }
        [StringLength(3)]
        public string? CaseText { get; set; }
        [StringLength(20)]
        public string? IsNullText { get; set; }
        public int? CoalesceValue { get; set; }
        public DateTime? CurrentDateTime { get; set; }
        public Guid? GeneratedId { get; set; }
        [StringLength(12)]
        public string? ConvertedDateText { get; set; }
    }
}
