// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace DockerPlayground.Models
{
    public partial class USP_ErrorResult
    {
        public int? TestColumn { get; set; }
    }
}
