// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace Ef7Playground.Models
{
    public partial class MultiSetResult
    {
        public int ShipperID { get; set; }
        public string CompanyName { get; set; } = default!;
        public string? Phone { get; set; }
    }
}
