// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScaffoldingPostgreSqlMultiSchemaTester.Models
{
    /// <summary>
    /// Bicycle assembly diagrams.
    /// </summary>
    public partial class Illustration
    {
        public Illustration()
        {
            Productmodelillustration = new HashSet<Productmodelillustration>();
        }

        /// <summary>
        /// Primary key for Illustration records.
        /// </summary>
        public int Illustrationid { get; set; }
        /// <summary>
        /// Illustrations used in manufacturing instructions. Stored as XML.
        /// </summary>
        public string Diagram { get; set; }
        public DateTime Modifieddate { get; set; }

        public virtual ICollection<Productmodelillustration> Productmodelillustration { get; set; }
    }
}