// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScaffoldingPostgreSqlMultiSchemaTester.Models
{
    /// <summary>
    /// Cross-reference table mapping product models and illustrations.
    /// </summary>
    public partial class Productmodelillustration
    {
        /// <summary>
        /// Primary key. Foreign key to ProductModel.ProductModelID.
        /// </summary>
        public int Productmodelid { get; set; }
        /// <summary>
        /// Primary key. Foreign key to Illustration.IllustrationID.
        /// </summary>
        public int Illustrationid { get; set; }
        public DateTime Modifieddate { get; set; }

        public virtual Illustration Illustration { get; set; }
        public virtual Productmodel Productmodel { get; set; }
    }
}