// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScaffoldingPostgreSqlMultiSchemaTester.Models
{
    /// <summary>
    /// Cross-reference table mapping products to related product documents.
    /// </summary>
    public partial class Productdocument
    {
        /// <summary>
        /// Product identification number. Foreign key to Product.ProductID.
        /// </summary>
        public int Productid { get; set; }
        public DateTime Modifieddate { get; set; }
        /// <summary>
        /// Document identification number. Foreign key to Document.DocumentNode.
        /// </summary>
        public string Documentnode { get; set; }

        public virtual Document DocumentnodeNavigation { get; set; }
        public virtual Product Product { get; set; }
    }
}