// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScaffoldingPostgreSqlMultiSchemaTester.Models
{
    /// <summary>
    /// Product model classification.
    /// </summary>
    public partial class Productmodel
    {
        public Productmodel()
        {
            Product = new HashSet<Product>();
            Productmodelillustration = new HashSet<Productmodelillustration>();
            Productmodelproductdescriptionculture = new HashSet<Productmodelproductdescriptionculture>();
        }

        /// <summary>
        /// Primary key for ProductModel records.
        /// </summary>
        public int Productmodelid { get; set; }
        /// <summary>
        /// Product model description.
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// Detailed product catalog information in xml format.
        /// </summary>
        public string Catalogdescription { get; set; }
        /// <summary>
        /// Manufacturing instructions in xml format.
        /// </summary>
        public string Instructions { get; set; }
        public Guid Rowguid { get; set; }
        public DateTime Modifieddate { get; set; }

        public virtual ICollection<Product> Product { get; set; }
        public virtual ICollection<Productmodelillustration> Productmodelillustration { get; set; }
        public virtual ICollection<Productmodelproductdescriptionculture> Productmodelproductdescriptionculture { get; set; }
    }
}