blank_issues_enabled: true
contact_links:
  - name: Issue with EF Core (runtime)
    url:  https://github.com/dotnet/efcore/issues/new/choose
    about: Please open issues relating to EF Core in dotnet/efcore.
