// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScaffoldingPostgreSqlMultiSchemaTester.Models
{
    /// <summary>
    /// Street address information for customers, employees, and vendors.
    /// </summary>
    public partial class Address
    {
        public Address()
        {
            Businessentityaddress = new HashSet<Businessentityaddress>();
            SalesorderheaderBilltoaddress = new HashSet<Salesorderheader>();
            SalesorderheaderShiptoaddress = new HashSet<Salesorderheader>();
        }

        /// <summary>
        /// Primary key for Address records.
        /// </summary>
        public int Addressid { get; set; }
        /// <summary>
        /// First street address line.
        /// </summary>
        public string Addressline1 { get; set; }
        /// <summary>
        /// Second street address line.
        /// </summary>
        public string Addressline2 { get; set; }
        /// <summary>
        /// Name of the city.
        /// </summary>
        public string City { get; set; }
        /// <summary>
        /// Unique identification number for the state or province. Foreign key to StateProvince table.
        /// </summary>
        public int Stateprovinceid { get; set; }
        /// <summary>
        /// Postal code for the street address.
        /// </summary>
        public string Postalcode { get; set; }
        /// <summary>
        /// Latitude and longitude of this address.
        /// </summary>
        public string Spatiallocation { get; set; }
        public Guid Rowguid { get; set; }
        public DateTime Modifieddate { get; set; }

        public virtual Stateprovince Stateprovince { get; set; }
        public virtual ICollection<Businessentityaddress> Businessentityaddress { get; set; }
        public virtual ICollection<Salesorderheader> SalesorderheaderBilltoaddress { get; set; }
        public virtual ICollection<Salesorderheader> SalesorderheaderShiptoaddress { get; set; }
    }
}