// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScaffoldingPostgreSqlMultiSchemaTester.Models
{
    /// <summary>
    /// Source of the ID that connects vendors, customers, and employees with address and contact information.
    /// </summary>
    public partial class Businessentity
    {
        public Businessentity()
        {
            Businessentityaddress = new HashSet<Businessentityaddress>();
            Businessentitycontact = new HashSet<Businessentitycontact>();
        }

        /// <summary>
        /// Primary key for all customers, vendors, and employees.
        /// </summary>
        public int Businessentityid { get; set; }
        public Guid Rowguid { get; set; }
        public DateTime Modifieddate { get; set; }

        public virtual Person Person { get; set; }
        public virtual Store Store { get; set; }
        public virtual Vendor Vendor { get; set; }
        public virtual ICollection<Businessentityaddress> Businessentityaddress { get; set; }
        public virtual ICollection<Businessentitycontact> Businessentitycontact { get; set; }
    }
}