// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScaffoldingPostgreSqlMultiSchemaTester.Models
{
    /// <summary>
    /// Lookup table containing the types of business entity contacts.
    /// </summary>
    public partial class Contacttype
    {
        public Contacttype()
        {
            Businessentitycontact = new HashSet<Businessentitycontact>();
        }

        /// <summary>
        /// Primary key for ContactType records.
        /// </summary>
        public int Contacttypeid { get; set; }
        /// <summary>
        /// Contact type description.
        /// </summary>
        public string Name { get; set; }
        public DateTime Modifieddate { get; set; }

        public virtual ICollection<Businessentitycontact> Businessentitycontact { get; set; }
    }
}