// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScaffoldingPostgreSqlMultiSchemaTester.Models
{
    /// <summary>
    /// Type of phone number of a person.
    /// </summary>
    public partial class Phonenumbertype
    {
        public Phonenumbertype()
        {
            Personphone = new HashSet<Personphone>();
        }

        /// <summary>
        /// Primary key for telephone number type records.
        /// </summary>
        public int Phonenumbertypeid { get; set; }
        /// <summary>
        /// Name of the telephone number type
        /// </summary>
        public string Name { get; set; }
        public DateTime Modifieddate { get; set; }

        public virtual ICollection<Personphone> Personphone { get; set; }
    }
}