// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScaffoldingPostgreSqlMultiSchemaTester.Models
{
    /// <summary>
    /// State and province lookup table.
    /// </summary>
    public partial class Stateprovince
    {
        public Stateprovince()
        {
            Address = new HashSet<Address>();
            Salestaxrate = new HashSet<Salestaxrate>();
        }

        /// <summary>
        /// Primary key for StateProvince records.
        /// </summary>
        public int Stateprovinceid { get; set; }
        /// <summary>
        /// ISO standard state or province code.
        /// </summary>
        public string Stateprovincecode { get; set; }
        /// <summary>
        /// ISO standard country or region code. Foreign key to CountryRegion.CountryRegionCode.
        /// </summary>
        public string Countryregioncode { get; set; }
        /// <summary>
        /// 0 = StateProvinceCode exists. 1 = StateProvinceCode unavailable, using CountryRegionCode.
        /// </summary>
        public bool? Isonlystateprovinceflag { get; set; }
        /// <summary>
        /// State or province description.
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// ID of the territory in which the state or province is located. Foreign key to SalesTerritory.SalesTerritoryID.
        /// </summary>
        public int Territoryid { get; set; }
        public Guid Rowguid { get; set; }
        public DateTime Modifieddate { get; set; }

        public virtual Countryregion CountryregioncodeNavigation { get; set; }
        public virtual Salesterritory Territory { get; set; }
        public virtual ICollection<Address> Address { get; set; }
        public virtual ICollection<Salestaxrate> Salestaxrate { get; set; }
    }
}