// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace Ef7Playground.Models
{
    public partial class CustOrdersDetailResult
    {
        [StringLength(40)]
        public string ProductName { get; set; } = default!;
        [Column("UnitPrice", TypeName = "money")]
        public decimal UnitPrice { get; set; }
        public short Quantity { get; set; }
        public int? Discount { get; set; }
        [Column("ExtendedPrice", TypeName = "money")]
        public decimal? ExtendedPrice { get; set; }
    }
}
