// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace Ef7Playground.Models
{
    public partial class EmployeeSalesbyCountryResult
    {
        [StringLength(15)]
        public string? Country { get; set; }
        [StringLength(20)]
        public string LastName { get; set; } = default!;
        [StringLength(10)]
        public string FirstName { get; set; } = default!;
        public DateTime? ShippedDate { get; set; }
        public int OrderID { get; set; }
        [Column("SaleAmount", TypeName = "money")]
        public decimal? SaleAmount { get; set; }
    }
}
