// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PostgresTester.Models
{
    public partial class EmployeeSalesbyCountryResult
    {
        [Column(""Country"")]
        public string Country { get; set; }
        [Column(""LastName"")]
        public string LastName { get; set; }
        [Column(""FirstName"")]
        public string FirstName { get; set; }
        [Column(""ShippedDate"")]
        public DateTime? ShippedDate { get; set; }
        [Column(""OrderID"")]
        public int? OrderID { get; set; }
        [Column(""Subtotal"")]
        public double? Subtotal { get; set; }
    }
}
