// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Npgsql;
using PostgresTester;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace PostgresTester
{
    public partial class NorthwindContext
    {
        private INorthwindContextProcedures _procedures;

        public virtual INorthwindContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new NorthwindContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public INorthwindContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<CustOrderHistResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<EmployeeSalesbyCountryResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<SalesbyYearResult>().HasNoKey().ToView(null);
        }
    }

    public partial class NorthwindContextProcedures : INorthwindContextProcedures
    {
        private readonly NorthwindContext _context;

        public NorthwindContextProcedures(NorthwindContext context)
        {
            _context = context;
        }

        public virtual async Task<List<CustOrderHistResult>> CustOrderHistAsync(string CustomerID, CancellationToken cancellationToken = default)
        {
            var npgsqlParameters = new []
            {
                new NpgsqlParameter
                {
                    ParameterName = "CustomerID",
                    Value = CustomerID ?? Convert.DBNull,
                    NpgsqlDbType = NpgsqlTypes.NpgsqlDbType.Char,
                },
            };
            var _ = await _context.SqlQueryAsync<CustOrderHistResult>("SELECT * FROM \"public\".\"CustOrderHist\" (@CustomerID)", npgsqlParameters, cancellationToken);

            return _;
        }

        public virtual async Task<List<EmployeeSalesbyCountryResult>> EmployeeSalesbyCountryAsync(DateTime? Beginning_Date, DateTime? Ending_Date, CancellationToken cancellationToken = default)
        {
            var npgsqlParameters = new []
            {
                new NpgsqlParameter
                {
                    ParameterName = "Beginning_Date",
                    Value = Beginning_Date ?? Convert.DBNull,
                    NpgsqlDbType = NpgsqlTypes.NpgsqlDbType.Timestamp,
                },
                new NpgsqlParameter
                {
                    ParameterName = "Ending_Date",
                    Value = Ending_Date ?? Convert.DBNull,
                    NpgsqlDbType = NpgsqlTypes.NpgsqlDbType.Timestamp,
                },
            };
            var _ = await _context.SqlQueryAsync<EmployeeSalesbyCountryResult>("SELECT * FROM \"public\".\"Employee Sales by Country\" (@Beginning_Date, @Ending_Date)", npgsqlParameters, cancellationToken);

            return _;
        }

        public virtual async Task<List<SalesbyYearResult>> SalesbyYearAsync(DateTime? Beginning_Date, DateTime? Ending_Date, CancellationToken cancellationToken = default)
        {
            var npgsqlParameters = new []
            {
                new NpgsqlParameter
                {
                    ParameterName = "Beginning_Date",
                    Value = Beginning_Date ?? Convert.DBNull,
                    NpgsqlDbType = NpgsqlTypes.NpgsqlDbType.Timestamp,
                },
                new NpgsqlParameter
                {
                    ParameterName = "Ending_Date",
                    Value = Ending_Date ?? Convert.DBNull,
                    NpgsqlDbType = NpgsqlTypes.NpgsqlDbType.Timestamp,
                },
            };
            var _ = await _context.SqlQueryAsync<SalesbyYearResult>("SELECT * FROM \"public\".\"Sales by Year\" (@Beginning_Date, @Ending_Date)", npgsqlParameters, cancellationToken);

            return _;
        }
    }
}
