// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace PostgresTester.Models;

public partial class ProductSalesFor1997
{
    public string? CategoryName { get; set; }

    public string? ProductName { get; set; }

    public double? ProductSales { get; set; }
}