// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PostgresTester.Models
{
    public partial class SalesbyYearResult
    {
        [Column(""ShippedDate"")]
        public DateTime? ShippedDate { get; set; }
        [Column(""OrderID"")]
        public int? OrderID { get; set; }
        [Column(""Subtotal"")]
        public double? Subtotal { get; set; }
        [Column(""Year"")]
        public int? Year { get; set; }
    }
}
