//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFCorePowerTools.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReverseEngineerLocale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReverseEngineerLocale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EFCorePowerTools.Locales.ReverseEngineerLocale", typeof(ReverseEngineerLocale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AddAdhocConnection {
            get {
                return ResourceManager.GetString("AddAdhocConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AddAdhocDatabaseConnection {
            get {
                return ResourceManager.GetString("AddAdhocDatabaseConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AddDatabaseConnection {
            get {
                return ResourceManager.GetString("AddDatabaseConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AddExternalDacPac {
            get {
                return ResourceManager.GetString("AddExternalDacPac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AddSchemasToFilter {
            get {
                return ResourceManager.GetString("AddSchemasToFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AlwaysIncludeAllDatabaseObjects {
            get {
                return ResourceManager.GetString("AlwaysIncludeAllDatabaseObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CannotGenerateCodeWhileDebugging {
            get {
                return ResourceManager.GetString("CannotGenerateCodeWhileDebugging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CannotUncheckPrimaryKey {
            get {
                return ResourceManager.GetString("CannotUncheckPrimaryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CheckOutputWindowForErrors {
            get {
                return ResourceManager.GetString("CheckOutputWindowForErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CheckOutputWindowForWarnings {
            get {
                return ResourceManager.GetString("CheckOutputWindowForWarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ChooseConfigurationFile {
            get {
                return ResourceManager.GetString("ChooseConfigurationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ChooseDatabaseConnection {
            get {
                return ResourceManager.GetString("ChooseDatabaseConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ChooseDatabaseObjects {
            get {
                return ResourceManager.GetString("ChooseDatabaseObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ChooseSchemas {
            get {
                return ResourceManager.GetString("ChooseSchemas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ChooseSqlServerDatabaseProject {
            get {
                return ResourceManager.GetString("ChooseSqlServerDatabaseProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CodeGeneration {
            get {
                return ResourceManager.GetString("CodeGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ConnectionName {
            get {
                return ResourceManager.GetString("ConnectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ConnectionSample {
            get {
                return ResourceManager.GetString("ConnectionSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ConnectionString {
            get {
                return ResourceManager.GetString("ConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ContextName {
            get {
                return ResourceManager.GetString("ContextName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ContextNameRequired {
            get {
                return ResourceManager.GetString("ContextNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CustomizeUsingHandlebars {
            get {
                return ResourceManager.GetString("CustomizeUsingHandlebars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DatabaseConnectionNotFoundCannotRefresh {
            get {
                return ResourceManager.GetString("DatabaseConnectionNotFoundCannotRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DbContextOnly {
            get {
                return ResourceManager.GetString("DbContextOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DbContextPath {
            get {
                return ResourceManager.GetString("DbContextPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DbContextSubNamespace {
            get {
                return ResourceManager.GetString("DbContextSubNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EntityTypesAndContext {
            get {
                return ResourceManager.GetString("EntityTypesAndContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EntityTypesOnly {
            get {
                return ResourceManager.GetString("EntityTypesOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EntityTypesPath {
            get {
                return ResourceManager.GetString("EntityTypesPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EntityTypesSubNamespace {
            get {
                return ResourceManager.GetString("EntityTypesSubNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FileLayout {
            get {
                return ResourceManager.GetString("FileLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FilterSchemas {
            get {
                return ResourceManager.GetString("FilterSchemas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Functions {
            get {
                return ResourceManager.GetString("Functions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string GenerateEFCoreModelInProject {
            get {
                return ResourceManager.GetString("GenerateEFCoreModelInProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string GeneratingCode {
            get {
                return ResourceManager.GetString("GeneratingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string GettingReadyToConnect {
            get {
                return ResourceManager.GetString("GettingReadyToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string IncludeConnectionStringGeneratedCode {
            get {
                return ResourceManager.GetString("IncludeConnectionStringGeneratedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string InstallEFCoreProviderPackageInProject {
            get {
                return ResourceManager.GetString("InstallEFCoreProviderPackageInProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string InstallingEFCoreProviderPackage {
            get {
                return ResourceManager.GetString("InstallingEFCoreProviderPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LoadingDatabaseObjects {
            get {
                return ResourceManager.GetString("LoadingDatabaseObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LoadingOptions {
            get {
                return ResourceManager.GetString("LoadingOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MapNodaTimeTypes {
            get {
                return ResourceManager.GetString("MapNodaTimeTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Mapping {
            get {
                return ResourceManager.GetString("Mapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MapSpatialTypes {
            get {
                return ResourceManager.GetString("MapSpatialTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ModelGeneratedSuccesfully {
            get {
                return ResourceManager.GetString("ModelGeneratedSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Namespace {
            get {
                return ResourceManager.GetString("Namespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NamespaceRequired {
            get {
                return ResourceManager.GetString("NamespaceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Naming {
            get {
                return ResourceManager.GetString("Naming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NewNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("NewNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NoPrimaryKey {
            get {
                return ResourceManager.GetString("NoPrimaryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PackageNotFoundInProject {
            get {
                return ResourceManager.GetString("PackageNotFoundInProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PluralizeSingularizeObjectNames {
            get {
                return ResourceManager.GetString("PluralizeSingularizeObjectNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string POCOEntities {
            get {
                return ResourceManager.GetString("POCOEntities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ReleaseNotes {
            get {
                return ResourceManager.GetString("ReleaseNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RemoveConstructorFromEntities {
            get {
                return ResourceManager.GetString("RemoveConstructorFromEntities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RemoveDefaultConstructor {
            get {
                return ResourceManager.GetString("RemoveDefaultConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RemoveNavigationsFromEntities {
            get {
                return ResourceManager.GetString("RemoveNavigationsFromEntities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RemoveSelectedConnection {
            get {
                return ResourceManager.GetString("RemoveSelectedConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RemoveSQLDefaultFromBoolColumns {
            get {
                return ResourceManager.GetString("RemoveSQLDefaultFromBoolColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ReportingResult {
            get {
                return ResourceManager.GetString("ReportingResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ReverseEngineerCompleted {
            get {
                return ResourceManager.GetString("ReverseEngineerCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SearchForObjects {
            get {
                return ResourceManager.GetString("SearchForObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SplitDbContextIntoConfigurationClasses {
            get {
                return ResourceManager.GetString("SplitDbContextIntoConfigurationClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SqlServerNoViewDefinitionRights {
            get {
                return ResourceManager.GetString("SqlServerNoViewDefinitionRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SQLServerVersionNotSupported {
            get {
                return ResourceManager.GetString("SQLServerVersionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string StoredProcedures {
            get {
                return ResourceManager.GetString("StoredProcedures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string StoredProceduresReturnList {
            get {
                return ResourceManager.GetString("StoredProceduresReturnList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Tables {
            get {
                return ResourceManager.GetString("Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UnableToAddConnection {
            get {
                return ResourceManager.GetString("UnableToAddConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UnableToAddToList {
            get {
                return ResourceManager.GetString("UnableToAddToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UnableToBuildSelectedDatabaseProject {
            get {
                return ResourceManager.GetString("UnableToBuildSelectedDatabaseProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UnableToRemoveConnection {
            get {
                return ResourceManager.GetString("UnableToRemoveConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UncheckedEFCoreVersionUsed {
            get {
                return ResourceManager.GetString("UncheckedEFCoreVersionUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UncheckingFileRemoved {
            get {
                return ResourceManager.GetString("UncheckingFileRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UnsupportedProvider {
            get {
                return ResourceManager.GetString("UnsupportedProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UseDataAnnotations {
            get {
                return ResourceManager.GetString("UseDataAnnotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UseEF6Pluralizer {
            get {
                return ResourceManager.GetString("UseEF6Pluralizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UseManyToManyEntity {
            get {
                return ResourceManager.GetString("UseManyToManyEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UseNamesFromDatabase {
            get {
                return ResourceManager.GetString("UseNamesFromDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UseNullableReferenceTypes {
            get {
                return ResourceManager.GetString("UseNullableReferenceTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UseRegularExpression {
            get {
                return ResourceManager.GetString("UseRegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UseSchemaFolders {
            get {
                return ResourceManager.GetString("UseSchemaFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UseTextSearch {
            get {
                return ResourceManager.GetString("UseTextSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Views {
            get {
                return ResourceManager.GetString("Views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string WhatToGenerate {
            get {
                return ResourceManager.GetString("WhatToGenerate", resourceCulture);
            }
        }
    }
}
