// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1633:File should have header", Justification = "Generated by tooling")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "Reviewed", Scope = "member", Target = "~M:EFCorePowerTools.Handlers.ReverseEngineer.RevEngWizardHandler.PickConfigDialogInitializeAsync~System.Threading.Tasks.Task{System.String}")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1629:Documentation text should end with a period", Justification = "Reviewed", Scope = "member", Target = "~M:EFCorePowerTools.Handlers.ReverseEngineer.RevEngWizardHandler.PickConfigDialogInitializeAsync~System.Threading.Tasks.Task{System.Collections.Generic.List{EFCorePowerTools.Common.Models.ConfigModel}}")]
[assembly: SuppressMessage("Major Code Smell", "S1854:Unused assignments should be removed", Justification = "Reviewed", Scope = "member", Target = "~M:EFCorePowerTools.Handlers.ReverseEngineer.RevEngWizardHandler.PickConfigDialogInitializeAsync~System.Threading.Tasks.Task{System.Collections.Generic.List{EFCorePowerTools.Common.Models.ConfigModel}}")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1124:DoNotUseRegions", Justification = "Reviewed.")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1123:Do not place regions within elements", Justification = "Reviewed")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements should appear in the correct order", Justification = "Reviewed")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "Reviewed", Scope = "member", Target = "~M:EFCorePowerTools.Wizard.WizardPage2.ShowAndAwaitUserResponse(System.Boolean)~System.ValueTuple{System.Boolean,EFCorePowerTools.Contracts.Views.PickTablesDialogResult}")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "Reviewed", Scope = "member", Target = "~M:EFCorePowerTools.Wizard.WizardPage1.OnConfigurationChange(EFCorePowerTools.Common.Models.ConfigModel)")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "Reviewed", Scope = "member", Target = "~M:EFCorePowerTools.Wizard.WizardDataViewModel.HandleTableSelectionThreeStateChange(System.Nullable{System.Boolean})")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1512:Single-line comments should not be followed by blank line", Justification = "Reviewed", Scope = "member", Target = "~M:EFCorePowerTools.Wizard.WizardDataViewModel.HandleTableSelectionThreeStateChange(System.Nullable{System.Boolean})")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1512:Single-line comments should not be followed by blank line", Justification = "Reviewed", Scope = "member", Target = "~M:EFCorePowerTools.Wizard.WizardDataViewModel.RemoveDatabaseConnection_CanExecute~System.Boolean")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "Reviewed", Scope = "member", Target = "~M:EFCorePowerTools.Wizard.WizardDataViewModel.RemoveDatabaseConnection_CanExecute~System.Boolean")]
[assembly: SuppressMessage("Major Code Smell", "S1144:Unused private types or members should be removed", Justification = "Reviewed")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1512:Single-line comments should not be followed by blank line", Justification = "Reviewed", Scope = "member", Target = "~M:EFCorePowerTools.Wizard.WizardPage2.#ctor(EFCorePowerTools.Wizard.WizardDataViewModel,EFCorePowerTools.Contracts.Wizard.IWizardView)")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "Reviewed", Scope = "member", Target = "~M:EFCorePowerTools.Wizard.WizardPage2.#ctor(EFCorePowerTools.Wizard.WizardDataViewModel,EFCorePowerTools.Contracts.Wizard.IWizardView)")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "Reviewed")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1204:Static elements should appear before instance elements", Justification = "Reviewed")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1515:Single-line comment should be preceded by blank line", Justification = "Reviewed")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1202:Elements should be ordered by access", Justification = "Reviewed")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules", "SA1512:Single-line comments should not be followed by blank line", Justification = "Reviewed")]
