// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1633:File should have header", Justification = "Generated by tooling")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:EFCorePowerTools.Handlers.ReverseEngineer.RevEngWizardHandler.PickConfigDialogInitializeAsync~System.Threading.Tasks.Task{System.String}")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1629:Documentation text should end with a period", Justification = "<Pending>", Scope = "member", Target = "~M:EFCorePowerTools.Handlers.ReverseEngineer.RevEngWizardHandler.PickConfigDialogInitializeAsync~System.Threading.Tasks.Task{System.Collections.Generic.List{EFCorePowerTools.Common.Models.ConfigModel}}")]
[assembly: SuppressMessage("Major Code Smell", "S1854:Unused assignments should be removed", Justification = "<Pending>", Scope = "member", Target = "~M:EFCorePowerTools.Handlers.ReverseEngineer.RevEngWizardHandler.PickConfigDialogInitializeAsync~System.Threading.Tasks.Task{System.Collections.Generic.List{EFCorePowerTools.Common.Models.ConfigModel}}")]
