// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScaffoldingPostgreSqlMultiSchemaTester.Models
{
    /// <summary>
    /// Customer credit card information.
    /// </summary>
    public partial class Creditcard
    {
        public Creditcard()
        {
            Personcreditcard = new HashSet<Personcreditcard>();
            Salesorderheader = new HashSet<Salesorderheader>();
        }

        /// <summary>
        /// Primary key for CreditCard records.
        /// </summary>
        public int Creditcardid { get; set; }
        /// <summary>
        /// Credit card name.
        /// </summary>
        public string Cardtype { get; set; }
        /// <summary>
        /// Credit card number.
        /// </summary>
        public string Cardnumber { get; set; }
        /// <summary>
        /// Credit card expiration month.
        /// </summary>
        public int Expmonth { get; set; }
        /// <summary>
        /// Credit card expiration year.
        /// </summary>
        public int Expyear { get; set; }
        public DateTime Modifieddate { get; set; }

        public virtual ICollection<Personcreditcard> Personcreditcard { get; set; }
        public virtual ICollection<Salesorderheader> Salesorderheader { get; set; }
    }
}