// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScaffoldingPostgreSqlMultiSchemaTester.Models
{
    /// <summary>
    /// Cross-reference table mapping people to their credit card information in the CreditCard table.
    /// </summary>
    public partial class Personcreditcard
    {
        /// <summary>
        /// Business entity identification number. Foreign key to Person.BusinessEntityID.
        /// </summary>
        public int Businessentityid { get; set; }
        /// <summary>
        /// Credit card identification number. Foreign key to CreditCard.CreditCardID.
        /// </summary>
        public int Creditcardid { get; set; }
        public DateTime Modifieddate { get; set; }

        public virtual Person Businessentity { get; set; }
        public virtual Creditcard Creditcard { get; set; }
    }
}