// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScaffoldingPostgreSqlMultiSchemaTester.Models
{
    /// <summary>
    /// Cross-reference table mapping sales orders to sales reason codes.
    /// </summary>
    public partial class Salesorderheadersalesreason
    {
        /// <summary>
        /// Primary key. Foreign key to SalesOrderHeader.SalesOrderID.
        /// </summary>
        public int Salesorderid { get; set; }
        /// <summary>
        /// Primary key. Foreign key to SalesReason.SalesReasonID.
        /// </summary>
        public int Salesreasonid { get; set; }
        public DateTime Modifieddate { get; set; }

        public virtual Salesorderheader Salesorder { get; set; }
        public virtual Salesreason Salesreason { get; set; }
    }
}