// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScaffoldingPostgreSqlMultiSchemaTester.Models
{
    /// <summary>
    /// Sales territory lookup table.
    /// </summary>
    public partial class Salesterritory
    {
        public Salesterritory()
        {
            Customer = new HashSet<Customer>();
            Salesorderheader = new HashSet<Salesorderheader>();
            Salesperson = new HashSet<Salesperson>();
            Salesterritoryhistory = new HashSet<Salesterritoryhistory>();
            Stateprovince = new HashSet<Stateprovince>();
        }

        /// <summary>
        /// Primary key for SalesTerritory records.
        /// </summary>
        public int Territoryid { get; set; }
        /// <summary>
        /// Sales territory description
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// ISO standard country or region code. Foreign key to CountryRegion.CountryRegionCode.
        /// </summary>
        public string Countryregioncode { get; set; }
        /// <summary>
        /// Geographic area to which the sales territory belong.
        /// </summary>
        public string Group { get; set; }
        /// <summary>
        /// Sales in the territory year to date.
        /// </summary>
        public decimal Salesytd { get; set; }
        /// <summary>
        /// Sales in the territory the previous year.
        /// </summary>
        public decimal Saleslastyear { get; set; }
        /// <summary>
        /// Business costs in the territory year to date.
        /// </summary>
        public decimal Costytd { get; set; }
        /// <summary>
        /// Business costs in the territory the previous year.
        /// </summary>
        public decimal Costlastyear { get; set; }
        public Guid Rowguid { get; set; }
        public DateTime Modifieddate { get; set; }

        public virtual Countryregion CountryregioncodeNavigation { get; set; }
        public virtual ICollection<Customer> Customer { get; set; }
        public virtual ICollection<Salesorderheader> Salesorderheader { get; set; }
        public virtual ICollection<Salesperson> Salesperson { get; set; }
        public virtual ICollection<Salesterritoryhistory> Salesterritoryhistory { get; set; }
        public virtual ICollection<Stateprovince> Stateprovince { get; set; }
    }
}