// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScaffoldingPostgreSqlMultiSchemaTester.Models
{
    /// <summary>
    /// Tax rate lookup table.
    /// </summary>
    public partial class Salestaxrate
    {
        /// <summary>
        /// Primary key for SalesTaxRate records.
        /// </summary>
        public int Salestaxrateid { get; set; }
        /// <summary>
        /// State, province, or country/region the sales tax applies to.
        /// </summary>
        public int Stateprovinceid { get; set; }
        /// <summary>
        /// 1 = Tax applied to retail transactions, 2 = Tax applied to wholesale transactions, 3 = Tax applied to all sales (retail and wholesale) transactions.
        /// </summary>
        public int Taxtype { get; set; }
        /// <summary>
        /// Tax rate amount.
        /// </summary>
        public decimal Taxrate { get; set; }
        /// <summary>
        /// Tax rate description.
        /// </summary>
        public string Name { get; set; }
        public Guid Rowguid { get; set; }
        public DateTime Modifieddate { get; set; }

        public virtual Stateprovince Stateprovince { get; set; }
    }
}