// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScaffoldingPostgreSqlMultiSchemaTester.Models
{
    /// <summary>
    /// Sales performance tracking.
    /// </summary>
    public partial class Salespersonquotahistory
    {
        /// <summary>
        /// Sales person identification number. Foreign key to SalesPerson.BusinessEntityID.
        /// </summary>
        public int Businessentityid { get; set; }
        /// <summary>
        /// Sales quota date.
        /// </summary>
        public DateTime Quotadate { get; set; }
        /// <summary>
        /// Sales quota amount.
        /// </summary>
        public decimal Salesquota { get; set; }
        public Guid Rowguid { get; set; }
        public DateTime Modifieddate { get; set; }

        public virtual Salesperson Businessentity { get; set; }
    }
}