// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScaffoldingPostgreSqlMultiSchemaTester.Models
{
    /// <summary>
    /// Employee pay history.
    /// </summary>
    public partial class Employeepayhistory
    {
        /// <summary>
        /// Employee identification number. Foreign key to Employee.BusinessEntityID.
        /// </summary>
        public int Businessentityid { get; set; }
        /// <summary>
        /// Date the change in pay is effective
        /// </summary>
        public DateTime Ratechangedate { get; set; }
        /// <summary>
        /// Salary hourly rate.
        /// </summary>
        public decimal Rate { get; set; }
        /// <summary>
        /// 1 = Salary received monthly, 2 = Salary received biweekly
        /// </summary>
        public int Payfrequency { get; set; }
        public DateTime Modifieddate { get; set; }

        public virtual Employee Businessentity { get; set; }
    }
}