// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScaffoldingPostgreSqlMultiSchemaTester.Models
{
    /// <summary>
    /// RÃ©sumÃ©s submitted to Human Resources by job applicants.
    /// </summary>
    public partial class Jobcandidate
    {
        /// <summary>
        /// Primary key for JobCandidate records.
        /// </summary>
        public int Jobcandidateid { get; set; }
        /// <summary>
        /// Employee identification number if applicant was hired. Foreign key to Employee.BusinessEntityID.
        /// </summary>
        public int? Businessentityid { get; set; }
        /// <summary>
        /// RÃ©sumÃ© in XML format.
        /// </summary>
        public string Resume { get; set; }
        public DateTime Modifieddate { get; set; }

        public virtual Employee Businessentity { get; set; }
    }
}