// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScaffoldingPostgreSqlMultiSchemaTester.Models
{
    /// <summary>
    /// Work shift lookup table.
    /// </summary>
    public partial class Shift
    {
        public Shift()
        {
            Employeedepartmenthistory = new HashSet<Employeedepartmenthistory>();
        }

        /// <summary>
        /// Primary key for Shift records.
        /// </summary>
        public int Shiftid { get; set; }
        /// <summary>
        /// Shift description.
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// Shift start time.
        /// </summary>
        public TimeOnly Starttime { get; set; }
        /// <summary>
        /// Shift end time.
        /// </summary>
        public TimeOnly Endtime { get; set; }
        public DateTime Modifieddate { get; set; }

        public virtual ICollection<Employeedepartmenthistory> Employeedepartmenthistory { get; set; }
    }
}