del Bricelam.EntityFrameworkCore.Pluralizer.dll 
del DacFxStrongTypedCore.dll 
del DacFxStrongTypedCore.pdb 
del ErikEJ.EntityFrameworkCore.SqlServer.Dacpac.dll 
del ErikEJ.EntityFrameworkCore.SqlServer.Dacpac.pdb 
del Humanizer.dll 
del Microsoft.Build.dll 
del Microsoft.Build.Framework.dll 
del Microsoft.Data.SqlClient.dll 
del Microsoft.Data.Tools.Schema.Sql.dll 
del Microsoft.Data.Tools.Utilities.dll 
del Microsoft.DotNet.PlatformAbstractions.dll 
del Microsoft.Identity.Client.dll 
del Microsoft.IdentityModel.JsonWebTokens.dll 
del Microsoft.IdentityModel.Logging.dll 
del Microsoft.IdentityModel.Protocols.dll 
del Microsoft.IdentityModel.Protocols.OpenIdConnect.dll 
del Microsoft.IdentityModel.Tokens.dll 
del Microsoft.SqlServer.Dac.dll Microsoft.SqlServer.Dac.Extensions.dll 
del Microsoft.SqlServer.TransactSql.ScriptDom.dll 
del Microsoft.SqlServer.Types.dll Microsoft.Win32.SystemEvents.dll 
del NetTopologySuite.dll 
del NetTopologySuite.IO.PostGis.dll 
del NetTopologySuite.IO.SqlServerBytes.dll 
del NodaTime.dll 
del RevEng.Shared.dll 
del RevEng.Shared.pdb 
del System.CodeDom.dll 
del System.ComponentModel.Composition.dll 
del System.Configuration.ConfigurationManager.dll 
del System.Drawing.Common.dll 
del System.IdentityModel.Tokens.Jwt.dll 
del System.Runtime.Caching.dll 
del System.Security.Cryptography.ProtectedData.dll 
del System.Security.Permissions.dll 
del System.Windows.Extensions.dll
