del DacFxStrongTypedCore.dll 
del DacFxStrongTypedCore.pdb 
del ErikEJ.EntityFrameworkCore.SqlServer.Dacpac.dll 
del ErikEJ.EntityFrameworkCore.SqlServer.Dacpac.pdb 
del Humanizer.dll 
del JetBrains.Annotations.dll 
del Microsoft.Build.dll 
del Microsoft.Build.Framework.dll 
del Microsoft.Data.Tools.Schema.Sql.dll 
del Microsoft.Data.Tools.Utilities.dll 
del Microsoft.SqlServer.Dac.dll 
del Microsoft.SqlServer.Dac.Extensions.dll 
del Microsoft.SqlServer.TransactSql.ScriptDom.dll 
del Microsoft.SqlServer.Types.dll 
del NetTopologySuite.dll 
del NetTopologySuite.IO.PostGis.dll 
del NetTopologySuite.IO.SqlServerBytes.dll 
del NodaTime.dll 
del Npgsql.NetTopologySuite.dll 
del Npgsql.NodaTime.dll 
del RevEng.Shared.dll 
del RevEng.Shared.pdb 
del System.ComponentModel.Composition.dll
