name: CLI Tool

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**/*'
      - '!.github/workflows/cli-tool.yml'
      - '!src/Core/**/*'
    branches:
      - 'master'
  pull_request:
    branches:
      - '*'

env:
  VERSION: ${{ github.run_number }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Build CLI 8
      run: dotnet build src/Core/efcpt.8/efcpt.8.csproj

    - name: Build CLI 9
      run: dotnet build src/Core/efcpt.9/efcpt.9.csproj
  
    - name: Package CLI 8
      if: startsWith(github.ref, 'refs/heads/master')
      run: dotnet pack src/Core/efcpt.8/efcpt.8.csproj -p:PackageVersion=8.1.${{ env.VERSION }}-nightly -p:InformationalVersion=8.1.${{ env.VERSION }}-nightly

    - name: Package CLI 9
      if: startsWith(github.ref, 'refs/heads/master')
      run: dotnet pack src/Core/efcpt.9/efcpt.9.csproj -p:PackageVersion=9.1.${{ env.VERSION }}-nightly -p:InformationalVersion=9.1.${{ env.VERSION }}-nightly
      
    - name: Core test project
      run: dotnet test src/Core/NUnitTestCore/NUnitTestCore.csproj
      continue-on-error: false

    - name: Publish NuGet
      if: startsWith(github.ref, 'refs/heads/master')
      run: dotnet nuget push **\erikej.*.nupkg --source 'https://api.nuget.org/v3/index.json' --api-key ${{ secrets.NUGET }} --skip-duplicate
