name: CLI Tool

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**/*'
      - '!.github/workflows/cli-tool.yml'
      - '!src/Core/**/*'
    branches:
      - 'master'
  pull_request:
    branches:
      - '*'

env:
  VERSION: ${{ github.run_number }}

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.304'

    - name: Package CLI 6
      run: dotnet pack src\Core\efcpt.6\efcpt.6.csproj -p:PackageVersion=6.1.${{ env.VERSION }}-nightly -p:InformationalVersion=6.1.${{ env.VERSION }}-nightly
  
    - name: Package CLI 8
      run: dotnet pack src\Core\efcpt.8\efcpt.8.csproj -p:PackageVersion=8.1.${{ env.VERSION }}-nightly -p:InformationalVersion=8.1.${{ env.VERSION }}-nightly

    - name: Package CLI 9
      run: dotnet pack src\Core\efcpt.9\efcpt.9.csproj -p:PackageVersion=9.1.${{ env.VERSION }}-nightly -p:InformationalVersion=9.1.${{ env.VERSION }}-nightly
      
    - name: Core test project
      run: dotnet test src\Core\NUnitTestCore\NUnitTestCore.csproj
      continue-on-error: false

    - name: Publish NuGet
      if: startsWith(github.ref, 'refs/heads/master')
      run: dotnet nuget push **\*.nupkg --source 'https://api.nuget.org/v3/index.json' --api-key ${{ secrets.NUGET }} --skip-duplicate
