name: Nupkg

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    permissions:
      id-token: write  # enable GitHub OIDC token issuance for this job

    steps:
    - uses: actions/checkout@v6

    - uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0.x'
  
    - name: Package Dacpac 8
      run: dotnet pack src\Nupkg\ErikEJ.EntityFrameworkCore.8.SqlServer.Dacpac\ErikEJ.EntityFrameworkCore.8.SqlServer.Dacpac.csproj

    - name: Package Dacpac 9
      run: dotnet pack src\Nupkg\ErikEJ.EntityFrameworkCore.9.SqlServer.Dacpac\ErikEJ.EntityFrameworkCore.9.SqlServer.Dacpac.csproj

    - name: Publish artifacts
      uses: actions/upload-artifact@v7
      with:
        name: Nupkg
        path: |
          **/*.nupkg

    - name: NuGet login (OIDC → temp API key)
      if: startsWith(github.ref, 'refs/heads/master')  
      uses: NuGet/login@v1
      id: login
      with:
          user: ${{ secrets.NUGET_USER }}

    - name: Publish NuGet
      if: startsWith(github.ref, 'refs/heads/master')
      run: dotnet nuget push **\${{ secrets.NUGET_USER }}.*.nupkg --source 'https://api.nuget.org/v3/index.json' --api-key ${{ steps.login.outputs.NUGET_API_KEY }} --skip-duplicate
      